# 语言
language: node_js
# 版本
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
# 分支
branches:
  only:
  - master
# install 脚本
install: yarn
# build 
script:
  - yarn lint
  - yarn build
  - yarn test
notifications:
  email:
    - 332006721@qq.com
  on_success: never
  on_failure: always